alias vim="nvim"
alias v="nvim"
alias vimrc="nvim /home/archie/.vimrc"
alias r="ranger"
alias n="ncmpcpp"
alias i3c="nvim /home/archie/.config/i3/config"
alias q="exit"
alias nb="newsboat"
alias nburls="nvim /home/archie/.config/newsboat/urls"
alias nm='neomutt'
alias bt='bluetoothctl'
