#!/bin/bash

# REMEMBER TO CHANGE WLP3S0 TO THE CORRECT WIFI DEVICE.
STATUS=$(cat /sys/class/net/wlp3s0/operstate)
GLYPH=

if [[ $STATUS == "down" ]]
then
	GLYPH="<span foreground='#ff0000' font=\"FontAwesome 13\"></span>"
elif [[ $STATUS == "up" ]]
then
	GLYPH="<span font=\"FontAwesome 13\"></span>"
fi

echo $GLYPH
