#!/bin/bash

STATUS=$(cat /sys/class/power_supply/BAT0/status)
CAPACITY=$(cat /sys/class/power_supply/BAT0/capacity)

EMPTY='[     ]'
TWENTY='[|    ]'
FORTY='[||   ]'
SIXTY="[|||  ]"
EIGHTY="[|||| ]"
HUNDRED="[|||||]"

COLOR='000000'

if  (( $CAPACITY == 100 || $CAPACITY > 80 ))
then
	GLYPH=$HUNDRED
elif (( $CAPACITY > 60 ))
then
	GLYPH=$EIGHTY
elif (( $CAPACITY > 40 ))
then
	GLYPH=$SIXTY
elif (( $CAPACITY > 20 ))
then
	GLYPH=$FORTY
elif (( $CAPACITY > 10 ))
then
	GLYPH=$TWENTY
	COLOR='f48f42'
elif (( $CAPACITY <= 10 ))
then
	GLYPH=$EMPTY
	COLOR='ff0000'
fi

if [[ $STATUS == "Charging" ]]
then
	COLOR='42c5f4'
fi

if [[ $STATUS == "Full" ]]
then
	COLOR='00cc00'
fi


# echo "<span foreground='$COLOR' font=\"FontAwesome 12\">$GLYPH</span>"
echo "<span foreground='#$COLOR' font=\"Spleen 14\">$GLYPH </span>"
