#!/bin/bash

PLAY=""
PAUSE=""

SONG="$(mpc current | sed -e 's/^\(.\{55\}\).*/\1/')"
STATUS=$(mpc status | grep -e paused -e playing | sed 's/].*$//g
; s/\[//g')

if [[ $STATUS == "playing" ]]
then
	SYMBOL=$PLAY
elif [[ $STATUS == "paused" ]]
then
	SYMBOL=$PAUSE
fi

echo "<span font=\"FontAwesome\">$SYMBOL</span> $SONG"
