#!/bin/bash

STATUS=$(cat /sys/class/power_supply/BAT0/status)
CAPACITY=$(cat /sys/class/power_supply/BAT0/capacity)

EMPTY=""
QUARTER=""
HALF=""
THREEQUARTER=""
FULL=""

COLOR='#000000'

if  (( $CAPACITY == 100 || $CAPACITY > 75 ))
then
	GLYPH=$FULL
elif (( $CAPACITY > 50 ))
then
	GLYPH=$THREEQUARTER
elif (( $CAPACITY > 25 ))
then
	GLYPH=$HALF
elif (( $CAPACITY > 10 ))
then
	GLYPH=$QUARTER
	COLOR='#f48f42'
elif (( $CAPACITY <= 10 ))
then
	GLYPH=$EMPTY
	COLOR='#ff0000'
fi

if [[ $STATUS == "Charging" ]]
then
	if [[ $GLYPH == $FULL ]]
	then
		COLOR='#0f9e19'
	else
		COLOR='#fff728'
	fi
fi

echo "<span foreground='$COLOR' font=\"FontAwesome 12\">$GLYPH</span> ($CAPACITY%) "
