#!/bin/sh

# DMENU="dmenu -i -sb '#eeeeee' -sf '#222222' -h 27"
DMENU="dmenu -i"
MOUNTPOINT=/run/media/$USER

# Copied entirely from Luke Smith (lukesmith.xyz).

# If dmenu is already running, don't run this script.
/usr/bin/pgrep -x dmenu && exit

# Get a list of unmounted mountable partitions
mountable=$(/usr/bin/lsblk -lp | /bin/grep "part $" | awk '{print $1, "(" $4 ")" }')
[[ "$mountable" = "" ]] && exit 1 # Exit if no mountable partitions

chosen=$(echo "$mountable" | $DMENU -p "Drive to mount: " | awk '{print $1}')
[[ "$chosen" = "" ]] && exit 1 # Exit if no drive selected

# If drive is found in /etc/fstab by mount, then the program will terminate
sudo mount "$chosen" && exit 0

mount_name=$(echo "usb" "sd" | $DMENU -p "Specify a mount name:" | awk '{print $1}')
[[ "$mount_name" = "" ]] && exit 1

if [[ ! -d $MOUNTPOINT$mount_name ]]; then
	sudo mkdir -p "$MOUNTPOINT$mount_name"
fi

sudo mount "$chosen" "$MOUNTPOINT$mount_name" && notify-send "$chosen mounted as $mount_name"
