#!/bin/bash

# Grabs current status of mpd. Used for lockScreen.sh

#Location of mpd statefile
STATEFILE=/home/archie/.config/mpd/state

if [[ ! -f $STATEFILE ]]
then
	echo "ERROR:$STATEFILE does not exist." >&2
fi

STATE=$( mpc | grep .*] | sed 's/].*//g; s/\[//g' )
echo $STATE
