#!/bin/bash

DELAY=0
DATE=$(date +%y-%m-%d-%H-%M)
SCREENSHOTTER="/usr/bin/import -window root"
SAVE_LOCATION="$HOME/Pictures/Screenshots/"
FILENAME="$SAVE_LOCATION$DATE.png"


usage() {
	/bin/cat << END
Usage: scrsht {DELAY/ms} {FILE DESTINATION}

Takes a screenshot after DELAY milliseconds. Set to 0 for no delay.
Specify a file destination and name to save there instead.

END
}

no-delay() {
	$SCREENSHOTTER $FILENAME
	exit 0
}

calc() { awk "BEGIN{print $*}"; }

#https://stackoverflow.com/questions/2210349/test-whether-string-is-a-valid-integer

if [[ $1 =~ ^-?[0-9]+$ ]]
then
	echo null >> /dev/null
else
	usage
	exit 1
fi

if [[ $1 == "0" ]]
then
	no-delay
fi

if [[ ! -z "$2" ]]
then
	FILENAME="$2"
fi

sleep $(calc $1/1000); $SCREENSHOTTER $FILENAME
