#!/bin/bash

#Lists all wifi-profiles and tries to load one.

#Grabs the dmenu config from .config/i3/config

bg_color=$(cat /home/archie/.config/i3/config | grep -e "set \$bg-color" | sed 's/.*#/#/g')
text_color=$(/bin/cat /home/archie/.config/i3/config | grep -e "set \$text-color" | sed 's/.*#/#/g')

CHOSEN_CONNECTION=$(/usr/bin/netctl list| tr -d ' ' | /usr/bin/dmenu -p "Pick a network:" -nb "$bg_color" -nf "$text_color" | sed 's/\*//g;s/\+//g')

/usr/bin/sudo /usr/bin/netctl stop-all
/usr/bin/sudo /usr/bin/netctl start $CHOSEN_CONNECTION;
if (( $? == 0 ))
then
	/usr/bin/notify-send "Wifi Connected" "Connected to $CHOSEN_CONNECTION" -t 2000
else
	/usr/bin/notify-send --ugency=critical "Wifi Not Connected" "Failed Connection to $CHOSEN_CONNECTION" -t 2000
fi
