#!/bin/bash

WALLPAPER=/home/$USER/.wallpaper

if [ ! -f "$1" ];
then
    echo "ERROR: $1 does not exist."
    exit 1
fi

IMGDIR=$(/usr/bin/realpath $(echo "$1" | sed 's/ /\\ /g'))

echo "Changing Wallpaper to $1..."
feh --bg-scale "$IMGDIR"
/usr/bin/ln -sf "$IMGDIR" "$WALLPAPER"
echo "Done."
echo "Deleting Lock Screen..."
rm /tmp/lockscreen.png
echo "Done"
exit 0
