#!/bin/bash

if [ ! -f "$1" ];
then
    echo "ERROR: $1 does not exist."
    exit 1
fi

IMGDIR=$(/usr/bin/realpath $(echo "$1" | sed 's/ /\\ /g'))

echo "Changing Wallpaper to $1..."
feh --bg-scale $IMGDIR
echo "$IMGDIR" > $HOME/.config/wallpaperChanger/currentWallpaper
echo "Done."
exit 0
